name: build-check

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install_dependencies
      run: sudo apt update && sudo apt install libevent-dev
    - name: build_dist_distclean
      run: |
           ./bootstrap
           ./configure
           make
           make dist
           ls dnsproxy-[0-9]*.tar.gz
           make distclean
    - name: build_install_run
      run: |
           ./bootstrap
           ./configure
           make
           sudo make install
           dnsproxy -V
           dnsproxy -h 2>&1 | egrep -iC10 usage
           